# Generated by Django 4.0.1 on 2022-02-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_author_alter_articles_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date_time',
            field=models.DateField(verbose_name='Время создания'),
        ),
    ]
