# Generated by Django 4.0.1 on 2022-02-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_articles_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
